apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-ticket-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-ticket-app
  template:
    metadata:
      labels:
        app: train-ticket-app
    spec:
      containers:
      - name: train-ticket-app
        image: train-ticket-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: train-ticket-app-service
spec:
  type: NodePort
  selector:
    app: train-ticket-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
